### ISSUE TITLE
PageRecyclerView作为RecyclerView的一个itemview时, 调用updateAll方法会导致 Indicator显示错乱             

### ISSUE THREAD

**Issue by realwqsz** [ckrgithub/PageRecyclerView#1]
原因应该是调用updateAll后, 内部是调用了notifyDataSetChanged ,导致PageRecyclerView自动滚动到了顶部, 但是PageRecyclerView内部的一些变量mScrollOffset, mCurrentPage 等变量没有 重置, 导致Indicator显示错乱

**Comment by ckrgithub** [comment]
好，我修复一下

**Comment by ckrgithub** [comment]
V1.0.9：已经修复数据源发生变化时引起的bug。提示：banner的数据没变的话不建议频繁调用updateAll()或notifyDataSetChanged()

**Comment by realwqsz** [comment]
使用V1.0.9版本还是会出现indicator错位的情况，见图
![device-2018-03-18-113724](https://user-images.githubusercontent.com/10068718/37562352-ef227140-2aa0-11e8-938d-72bb30ee47c9.png)

**Comment by ckrgithub** [comment]
@androrz 详细的说下使用条件是怎样的？比如：1.用了竖直方向的PageView；2.是否启用无限轮播；3.数据源是否在滑动分页时有变化。

**Comment by ckrgithub** [comment]
允许的话，可以发个demo给我看看。本人qq是2448224046。

**Comment by realwqsz** [comment]
@ckrgithub 我是使用的水平方向的pageview，没有启用无限轮播， 并且pageview是作为RecyclerView的一个itemview使用的，类似与对话列表的一种view 类型， 外部RecyclerView页面滚动的时候可能频繁得重新设置数据到PageView上去

**Comment by ckrgithub** [comment]
这个已经解决了，我也写过demo测试，重新设置数据到PageView时，只需要调用updateAll()，不需要调用setCurrentItem()
