### ISSUE TITLE
设置的轮播，我只有8条数据，打印每次都是12条

### ISSUE THREAD

**Issue by liguangze** [ckrgithub/PageRecyclerView#11]
app:autosize="false"
   app:page_column="3"
   app:page_row="2"
app:layout_flag="grid"

   pageView.updateAll(listEnterprise);//更新数据   我集合里面就8条数据，但是super.getItemCount()打印每次都是12条，导致每次都多显示，啥原因呢

**Comment by ckrgithub** [comment]
因为，当数据没占满一页时，用null数据去填充。所以每页的数据有2 * 3=6条，n页就2 * 3 * n(当n=2)=12条。
getRawItemCount(): 这个是得到原始的数据；
getItemCount(): 得到改造后的数据 @liguangze

**Comment by liguangze** [comment]
并且每次左滑，右划的时候，图片自己还是会变小呢app:autosize="true"，设置了这个属性


假如我app:autosize="false" ，这样，又会导致了每页只显示两条，可以滑动好几页，但是下面的小圆点只有两页，按理说应该是设置成true，但是为什么左右滑动图片就越来越小，一直到没有了，求大神

**Comment by ckrgithub** [comment]
> 并且每次左滑，右划的时候，图片自己还是会变小呢app:autosize="true"，设置了这个属性
> 
> 假如我app:autosize="false" ，这样，又会导致了每页只显示两条，可以滑动好几页，但是下面的小圆点只有两页，按理说应该是设置成true，但是为什么左右滑动图片就越来越小，一直到没有了，求大神

截个图看看

**Comment by liguangze** [comment]
![rrr 20181105155627](https://user-images.githubusercontent.com/10549682/47985035-692d3a00-e113-11e8-9522-29bec16131e6.png)
![rr 20181105155558](https://user-images.githubusercontent.com/10549682/47985044-6fbbb180-e113-11e8-8910-3005c2e03295.png)


      <com.ckr.pageview.view.PageView
                        android:id="@+id/pageView"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        app:autosize="true"
                        app:layout_flag="grid"
                        app:page_column="3"
                        app:page_row="2"
                        app:selected_indicator_color="@color/main_red"
                        app:selected_indicator_diameter="@dimen/dp_6"
                        app:unselected_indicator_color="@color/home_view"
                        app:unselected_indicator_diameter="@dimen/dp_6"
                       />



加载的是网络图片

**Comment by liguangze** [comment]
这个是属性设置，上面是第一次加载的图片，下面的是我左右滑动就是下面的效果了，
   @Override
    protected void convert(MainHolder holder, int originalPos, EnterpriseBean.CompanyInfosBean originalItem, int adjustedPos, EnterpriseBean.CompanyInfosBean adjustedItem) {

        try {
            if (originalItem.getImageUrl()!=null && holder.imageView!= null) {
                ImageLoaderUtils.displayimage(mContext, holder.imageView, originalItem.getImageUrl());
            }
        } catch (Exception e) {
            holder.imageView.setVisibility(View.GONE);

            e.printStackTrace();

        }
    }

adapter的逻辑，剩下的demo跟你的都一样

**Comment by ckrgithub** [comment]
> ![rrr 20181105155627](https://user-images.githubusercontent.com/10549682/47985035-692d3a00-e113-11e8-9522-29bec16131e6.png)
> ![rr 20181105155558](https://user-images.githubusercontent.com/10549682/47985044-6fbbb180-e113-11e8-8910-3005c2e03295.png)
> 
> ```
>   <com.ckr.pageview.view.PageView
>                     android:id="@+id/pageView"
>                     android:layout_width="wrap_content"
>                     android:layout_height="wrap_content"
>                     app:autosize="true"
>                     app:layout_flag="grid"
>                     app:page_column="3"
>                     app:page_row="2"
>                     app:selected_indicator_color="@color/main_red"
>                     app:selected_indicator_diameter="@dimen/dp_6"
>                     app:unselected_indicator_color="@color/home_view"
>                     app:unselected_indicator_diameter="@dimen/dp_6"
>                    />
> ```
> 加载的是网络图片


固定下宽高值试试
![df746197-febb-4465-b41c-0cd9f116f9b1](https://user-images.githubusercontent.com/18225851/47985672-603d6800-e115-11e8-9b3e-264690d44f36.png)

**Comment by liguangze** [comment]
在adapter的item里面宽高设置了
            <LinearLayout
                android:gravity="center"
                android:orientation="horizontal"
                android:layout_width="@dimen/dp_108"
                android:layout_height="@dimen/dp_45">

                <ImageView
                    android:id="@+id/item_image"
                    android:src="@drawable/qiyelogo"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"/>

            </LinearLayout>


然后在  <com.ckr.pageview.view.PageView
                    android:id="@+id/pageView"
                  android:layout_width="@dimen/dp_260"
                        android:layout_height="@dimen/dp_160"
                    app:autosize="true"
                    app:layout_flag="grid"
                    app:page_column="3"
                    app:page_row="2"
                    app:selected_indicator_color="@color/main_red"
                    app:selected_indicator_diameter="@dimen/dp_6"
                    app:unselected_indicator_color="@color/home_view"
                    app:unselected_indicator_diameter="@dimen/dp_6"
                   />

也设置了，也不好使，我发现就是前4张会变小，后4张不会呢，第一页只显示了6个

**Comment by ckrgithub** [comment]
> 在adapter的item里面宽高设置了
> ```
>             <ImageView
>                 android:id="@+id/item_image"
>                 android:src="@drawable/qiyelogo"
>                 android:layout_width="wrap_content"
>                 android:layout_height="wrap_content"/>
> 
>         </LinearLayout>
> ```
> 然后在 <com.ckr.pageview.view.PageView
> android:id="@+id/pageView"
> android:layout_width="@dimen/dp_260"
> android:layout_height="@dimen/dp_160"
> app:autosize="true"
> app:layout_flag="grid"
> app:page_column="3"
> app:page_row="2"
> app:selected_indicator_color="@color/main_red"
> app:selected_indicator_diameter="@dimen/dp_6"
> app:unselected_indicator_color="@color/home_view"
> app:unselected_indicator_diameter="@dimen/dp_6"
> />
> 
> 也设置了，也不好使，我发现就是前4张会变小，后4张不会呢，第一页只显示了6个

**Comment by ckrgithub** [comment]
> 在adapter的item里面宽高设置了
> ```
>             <ImageView
>                 android:id="@+id/item_image"
>                 android:src="@drawable/qiyelogo"
>                 android:layout_width="wrap_content"
>                 android:layout_height="wrap_content"/>
> 
>         </LinearLayout>
> ```
> 然后在 <com.ckr.pageview.view.PageView
> android:id="@+id/pageView"
> android:layout_width="@dimen/dp_260"
> android:layout_height="@dimen/dp_160"
> app:autosize="true"
> app:layout_flag="grid"
> app:page_column="3"
> app:page_row="2"
> app:selected_indicator_color="@color/main_red"
> app:selected_indicator_diameter="@dimen/dp_6"
> app:unselected_indicator_color="@color/home_view"
> app:unselected_indicator_diameter="@dimen/dp_6"
> />
> 
> 也设置了，也不好使，我发现就是前4张会变小，后4张不会呢，第一页只显示了6个

log截图看看。记得PageView要设置宽高

**Comment by liguangze** [comment]
能留个qq吗，或者你加下我 429475006

**Comment by liguangze** [comment]
问题已经解决，感谢开源！！！！！！！！
