### ISSUE TITLE
拉到顶后继续滑动，然后第一次的点击事件无法响应？

### ISSUE THREAD

**Issue by qhyuan1992** [ckrgithub/PageRecyclerView#12]
发现个bug，拉到顶后继续滑动，然后接下来的第一次的点击事件无法响应？

**Comment by ckrgithub** [comment]
> 发现个bug，拉到顶后继续滑动，然后接下来的第一次的点击事件无法响应？

应该是代码把点击事件置空了吧。截个图看看

**Comment by qhyuan1992** [comment]
@ckrgithub  谢谢，试下你的demo里面的 水平网格那个左右翻页网格。正常情况下是可以长按弹出取消的。然后做以下操作：
现在将页面定位到第一页，继续向左拉（已经到最左了）。然后再长按item无效果。第二次按下才正常

**Comment by qhyuan1992** [comment]
我使用了系统的RecyclerView和PagerSnapHelper好像也有类似的问题？我看是这样操作后手指抬起，RecyclerView仍处于DRAGING状态导致点击没有传下去，原因好像是SnapHelper在到顶后计算fling有问题，我正在查这个问题

**Comment by ckrgithub** [comment]
> @ckrgithub 谢谢，试下你的demo里面的 水平网格那个左右翻页网格。正常情况下是可以长按弹出取消的。然后做以下操作：
> 现在将页面定位到第一页，继续向左拉（已经到最左了）。然后再长按item无效果。第二次按下才正常

确实，我看看如何修复

**Comment by ckrgithub** [comment]
> 我使用了系统的RecyclerView和PagerSnapHelper好像也有类似的问题？我看是这样操作后手指抬起，RecyclerView仍处于DRAGING状态导致点击没有传下去，原因好像是SnapHelper在到顶后计算fling有问题，我正在查这个问题

bug已修复，请pull最新代码验证下。

**Comment by ckrgithub** [comment]
具体思路如下：
![1](https://user-images.githubusercontent.com/18225851/48950204-5a4ce100-ef75-11e8-9bdb-2a532be232ab.png)
![2](https://user-images.githubusercontent.com/18225851/48950205-5e78fe80-ef75-11e8-96cf-f26e85919558.png)
![3](https://user-images.githubusercontent.com/18225851/48950214-62a51c00-ef75-11e8-9e2f-13a34d6180bc.png)

**Comment by qhyuan1992** [comment]
赞👍
