### ISSUE TITLE
第二页item不满一页滑不了一整页

### ISSUE THREAD

**Issue by debughao** [ckrgithub/PageRecyclerView#3]
假如一页有16个item，第二页有4个，滑倒第二页只能滑动到最后一项。显示的是第一页部分Item和第二页item。

**Comment by ckrgithub** [comment]
我这里只处理了一页最多2*4=8个item,若要一页16个，可以自定义位置调整的功能，可以参考PosUtil类

**Comment by debughao** [comment]
等于是数据不足一页 用空白布局填充吧

**Comment by ckrgithub** [comment]
@debughao  今天刚试了一下你的需求，是可以翻页的，但item位置就不提供调整工具。下一个版本：就不限制一页的个数。

**Comment by ckrgithub** [comment]
![pic1](https://user-images.githubusercontent.com/18225851/38122097-914ffd12-3405-11e8-9c48-be25bed31391.png)
![pic2](https://user-images.githubusercontent.com/18225851/38122105-9c21c36a-3405-11e8-98e2-365e316e6033.png)

**Comment by ckrgithub** [comment]
![pic1_proc](https://user-images.githubusercontent.com/18225851/38122172-0eafd9e4-3406-11e8-9b57-0722d00ace0c.jpg)
![pic2_proc](https://user-images.githubusercontent.com/18225851/38122161-0520eb3e-3406-11e8-89de-744c68a35376.jpg)
