### ISSUE TITLE
能追加个属性吗 clipToPadding

### ISSUE THREAD

**Issue by mengzhidaren** [ckrgithub/PageRecyclerView#4]
需求要看到pageView 两边 page 的边缘    你要有时间能加翻页动画最佳了

**Comment by ckrgithub** [comment]
好！这两天加上clipToPadding,有空再加动画

**Comment by ckrgithub** [comment]
已加

**Comment by mengzhidaren** [comment]
我在布局里固定高度后  itemView里也固定高度后会有被遮挡的BUG  改为match_parent就正常了        你布局里的wrap_content 会多一次高度计算  在性能上有所消耗   最好在自已定view里传参 来决定高度

**Comment by ckrgithub** [comment]
我看一下，是固定PageView和ItemView高度？

**Comment by ckrgithub** [comment]
若指示器位于PageRecyclerView下方，固定PageView的高度=ItemView的高度*页的行数pageRow + 
IndicatorContainer的高度；若指示器是覆盖在PageRecyclerView上面，固定PageView的高度=ItemView的高度*页的行数pageRow。我试过了，好像没有你说的bug，不知道有没有理解对你的意思。

**Comment by mengzhidaren** [comment]
和指示器没关系 ， 我就没用到指示器 ，是recyclerView的内容高度计算错了 ， 改为match_parent就正常了

**Comment by ckrgithub** [comment]
请详细说明下，固定哪些view的高度？另外，使用最新的implementation 'ckrjfrog.Page:PageView:1.1.1'

**Comment by ckrgithub** [comment]
翻页动画已添加
