### ISSUE TITLE
smoothScrollBy 方法duration为0时 某些平板上失效

### ISSUE THREAD

**Issue by debughao** [ckrgithub/PageRecyclerView#5]
scrollToPage 方法smoothScroll设为false后 smoothScrollBy(moveX, 0, 0);没有产生滑动效果。

**Comment by ckrgithub** [comment]
我这边没有平板，调试不了！你简单的调试一下，比如：调用setCurrentItem(1,false)后，把log输出来给我看看

**Comment by debughao** [comment]
E/PageLog: PageRecyclerView--->scrollToPage: moveX:776
 E/PageLog: PageRecyclerView--->smoothScrollBy,dx:776,dy:0,duration0
D/PageLog: PageRecyclerView--->onScrollStateChanged,mScrollState:2
 D/PageLog: PageRecyclerView--->scrollToPage: mCurrentPage:0,page:1

**Comment by ckrgithub** [comment]
对了！你所说的没有产生滑动效果，意思是没有翻到下一页么？我理解的滑动效果是设置为true才有的

**Comment by debughao** [comment]
是的 没有翻到下一页， 我找了个系统6.0的平板是正常的，而系统5.1的平板是代码没起作用

**Comment by ckrgithub** [comment]
嗯嗯，我看看5.0源码先！

**Comment by ckrgithub** [comment]
@debughao 你的log就只有四行么？我手机测试输出的log有9行:

E/PageLog: PageRecyclerView--->scrollToPage: moveX:1080
E/PageLog: PageRecyclerView--->smoothScrollBy,dx:1080,dy:0,duration0
D/PageLog: PageRecyclerView--->onScrollStateChanged,mScrollState:2
D/PageLog: PageRecyclerView--->scrollToPage: mCurrentPage:0,page:1
D/PageLog: PageRecyclerView--->onScrolled:mScrollOffset:1080,mCurrentPage:0,mDragOffset:0,forwardDirection:true,mScrollWidth:1080
D/PageLog: PageRecyclerView--->onScrolled,mCurrentPage:1
D/PageLog: PageRecyclerView--->onScrollStateChanged,mScrollState:0
D/PageLog: PageRecyclerView--->isSliding=true,deltaX:0,mScrollOffset:1080
D/PageLog: PageRecyclerView--->move,deltaX:0,mCurrentPage:1

**Comment by ckrgithub** [comment]
我看了22.2.1和25.3.0源码，感觉hresult计算的问题，导致onScrolled()没被调用
![1](https://user-images.githubusercontent.com/18225851/38244644-ebeadd94-376d-11e8-893d-693698f86a55.png)
![2](https://user-images.githubusercontent.com/18225851/38244653-f30f1d10-376d-11e8-9e90-6dbbc731b82c.png)
![3](https://user-images.githubusercontent.com/18225851/38244665-fa59d592-376d-11e8-85e8-e45fbfcd0f1e.png)
![4](https://user-images.githubusercontent.com/18225851/38244817-65547c76-376e-11e8-9dba-708f679893cb.png)

**Comment by debughao** [comment]
感觉是和OverScroller有关。只有时间间隔设置为0才会在我的系统6.0以下的平板出问题。

![qq 20180404150211](https://user-images.githubusercontent.com/10276104/38293196-32de778c-3819-11e8-9861-8aea4861a309.png)

![qq 20180404150411](https://user-images.githubusercontent.com/10276104/38293286-82493b40-3819-11e8-9478-c2819113e980.png)
我已经通过把时间间隔设置非常小达到了smoothScrollBy(moveX, 0, 0);的效果

**Comment by ckrgithub** [comment]
我也觉得是OverScroll问题，其实主要流程是，startScroll->ViewFlinger.run->computeScrollOffset->abortAnimation->scrollby->layoutManager的计算,不过overscroll源码几乎一样，所以有点怀疑是平板的源码被改了

**Comment by debughao** [comment]
还有个快速滑动时  onPageSelected可能不会触发的bug。 可以看下log position 7到8时。
    D/PageFragment: onPageScrollStateChanged() called with: state = [0]
            D/PageFragment: onPageScrollStateChanged() called with: state = [1]
            D/PageFragment: onPageScrolled() called with: position = [6], positionOffset = [0.46], positionOffsetPixels = [412]
            D/PageFragment: onPageScrolled() called with: position = [6], positionOffset = [0.66], positionOffsetPixels = [592]
            D/PageFragment: onPageScrolled() called with: position = [6], positionOffset = [0.73], positionOffsetPixels = [655]
            D/PageFragment: onPageScrollStateChanged() called with: state = [2]
            D/PageFragment: onPageScrolled() called with: position = [6], positionOffset = [0.75], positionOffsetPixels = [679]
            D/PageFragment: onPageScrolled() called with: position = [6], positionOffset = [0.91], positionOffsetPixels = [815]
            D/PageFragment: onPageScrolled() called with: position = [6], positionOffset = [0.97], positionOffsetPixels = [874]
            D/PageFragment: onPageScrolled() called with: position = [6], positionOffset = [0.99], positionOffsetPixels = [894]
            D/PageFragment: onPageScrolled() called with: position = [6], positionOffset = [1.0], positionOffsetPixels = [899]
            D/PageFragment: onPageScrolled() called with: position = [7], positionOffset = [0.0], positionOffsetPixels = [0]
            D/PageFragment: onPageSelected() called with: position = [7]
            D/PageFragment: onPageScrollStateChanged() called with: state = [0]
            D/PageFragment: onPageScrollStateChanged() called with: state = [1]
            D/PageFragment: onPageScrolled() called with: position = [7], positionOffset = [0.6], positionOffsetPixels = [536]
            D/PageFragment: onPageScrolled() called with: position = [7], positionOffset = [0.68], positionOffsetPixels = [616]
            D/PageFragment: onPageScrolled() called with: position = [7], positionOffset = [0.83], positionOffsetPixels = [749]
            D/PageFragment: onPageScrollStateChanged() called with: state = [2]
            D/PageFragment: onPageScrolled() called with: position = [7], positionOffset = [0.84], positionOffsetPixels = [759]
            D/PageFragment: onPageScrolled() called with: position = [7], positionOffset = [0.92], positionOffsetPixels = [824]
            D/PageFragment: onPageScrolled() called with: position = [7], positionOffset = [0.96], positionOffsetPixels = [863]
            D/PageFragment: onPageScrolled() called with: position = [7], positionOffset = [0.98], positionOffsetPixels = [884]
            D/PageFragment: onPageScrolled() called with: position = [7], positionOffset = [0.99], positionOffsetPixels = [893]
            D/PageFragment: onPageScrollStateChanged() called with: state = [1]
            D/PageFragment: onPageScrolled() called with: position = [8], positionOffset = [0.3], positionOffsetPixels = [268]
            D/PageFragment: onPageScrolled() called with: position = [8], positionOffset = [0.67], positionOffsetPixels = [602]
            D/PageFragment: onPageScrolled() called with: position = [8], positionOffset = [0.77], positionOffsetPixels = [693]
            D/PageFragment: onPageScrolled() called with: position = [8], positionOffset = [0.79], positionOffsetPixels = [711]
            D/PageFragment: onPageScrollStateChanged() called with: state = [2]
            D/PageFragment: onPageScrolled() called with: position = [8], positionOffset = [0.81], positionOffsetPixels = [732]
            D/PageFragment: onPageScrolled() called with: position = [8], positionOffset = [0.85], positionOffsetPixels = [764]
            D/PageFragment: onPageScrolled() called with: position = [8], positionOffset = [0.88], positionOffsetPixels = [791]
            D/PageFragment: onPageScrolled() called with: position = [8], positionOffset = [0.9], positionOffsetPixels = [813]
            D/PageFragment: onPageScrollStateChanged() called with: state = [1]
            D/PageFragment: onPageScrolled() called with: position = [9], positionOffset = [0.04], positionOffsetPixels = [37]
            D/PageFragment: onPageScrolled() called with: position = [9], positionOffset = [0.38], positionOffsetPixels = [342]
            D/PageFragment: onPageScrolled() called with: position = [9], positionOffset = [0.69], positionOffsetPixels = [621]
            D/PageFragment: onPageScrolled() called with: position = [9], positionOffset = [0.9], positionOffsetPixels = [809]
            D/PageFragment: onPageScrollStateChanged() called with: state = [2]
            D/PageFragment: onPageScrolled() called with: position = [9], positionOffset = [0.92], positionOffsetPixels = [830]
            D/PageFragment: onPageScrolled() called with: position = [9], positionOffset = [0.98], positionOffsetPixels = [886]
            D/PageFragment: onPageScrolled() called with: position = [9], positionOffset = [1.0], positionOffsetPixels = [899]
            D/PageFragment: onPageScrolled() called with: position = [10], positionOffset = [0.0], positionOffsetPixels = [0]
            D/PageFragment: onPageSelected() called with: position = [10]
            D/PageFragment: onPageScrollStateChanged() called with: state = [0]
            D/PageFragment: onPageScrollStateChanged() called with: state = [1]
            D/PageFragment: onPageScrolled() called with: position = [10], positionOffset = [0.45], positionOffsetPixels = [405]
            D/PageFragment: onPageScrolled() called with: position = [10], positionOffset = [0.89], positionOffsetPixels = [803]
            D/PageFragment: onPageScrolled() called with: position = [10], positionOffset = [0.92], positionOffsetPixels = [825]
            D/PageFragment: onPageScrollStateChanged() called with: state = [2]
            D/PageFragment: onPageScrolled() called with: position = [10], positionOffset = [0.96], positionOffsetPixels = [863]
            D/PageFragment: onPageScrolled() called with: position = [10], positionOffset = [0.99], positionOffsetPixels = [894]
            D/PageFragment: onPageScrolled() called with: position = [11], positionOffset = [0.0], positionOffsetPixels = [0]
            D/PageFragment: onPageSelected() called with: position = [11]

**Comment by ckrgithub** [comment]
894,893一个像素只差，今晚修复一下

**Comment by ckrgithub** [comment]
@debughao 快速滑动的bug已修复

**Comment by ckrgithub** [comment]
![1](https://user-images.githubusercontent.com/18225851/38318058-137f5c2e-3861-11e8-9864-ef9a798abca5.png)
你可以改为这样：
![default](https://user-images.githubusercontent.com/18225851/38319018-67d02c3e-3863-11e8-918c-d41d5f6fc10d.png)

**Comment by ckrgithub** [comment]
smoothScrollBy(moveX,0,0)改为scrollBy(moveX,0)，6.0以下的平板应该没问题了吧？
