### ISSUE TITLE
关于水平网格分页的效果

### ISSUE THREAD

**Issue by 1ibo** [ckrgithub/PageRecyclerView#8]
你好，我跑demo，水平网格分页（HG）的item顺序和screenRecorder里面的Screenshot_2.gif不一致，我的效果是上面一行（0，2，4，6），下面一行（1，3，5，7），而Screenshot_2.gif里面的顺序是上面一行（0，1，2，3），下面一行（2，4，6，8），请问是什么原因呢，是不是什么参数没有设置？

**Comment by ckrgithub** [comment]
@1ibo adapter要继承BasePageAdapter，BasePageAdapte有处理item顺序转换，具体可看源码，如：adjustPosition(index)

**Comment by 1ibo** [comment]
好的，谢谢
