### ISSUE TITLE
调用updateAll方法后通过setCurrentItem设置当前页有时候并不能生效

### ISSUE THREAD

**Issue by realwqsz** [ckrgithub/PageRecyclerView#9]
我有这样一个场景，需要根据云端返回数据，重新绑定数据，并将PageView翻到指定页。
`mListAdapter = new MainAdapter(ListWidgetActivity.this, R.layout.item_pager_view);
mPageView.setAdapter(mListAdapter);
mListAdapter.updateAll(mListData);
mPageView.setCurrentItem(targetPage, false);`
我每次收到云端数据后都这样操作，indicator能正常移动，但是有时候列表数据却不变。

**Comment by ckrgithub** [comment]
@androrz 重新绑定数据只需要调用pageView.updateAll()就可以了，会默认定位到更新数据前的页面。你最好用ckrjfrog.Page:PageView:1.2.4最新的试试
